#!/bin/bash

#
# Docker-powered MSSQL Check script (simple login/pass auth)
#

if [[ -z "$1" || -z "$2" || -z "$3" || -z "$4" || -z "$5" || -z "$6" ]]; then
  echo "Required credentials: MSSQL_HOST, MSSQL_DB, MSSQL_USER, MSSQL_PASS, MSSQL_QUERY and MSSQL_CHECK_REGEXP as script arguments"
  echo "e.g. ./checkmssql db.example.com mydb sqluser sqlpassword 'select getdate()' '[0-9]{4}\-[0-9]{2}\-[0-9]{2}'"
  exit 1
fi

export MSSQL_HOST="$1"
export MSSQL_DB="$2"
export MSSQL_USER="$3"
export MSSQL_PASS="$4"
export MSSQL_QUERY="$5"
export MSSQL_CHECK_REGEXP="$6"

#
# Enable this for debug information...
#
#echo MSSQL_HOST=$MSSQL_HOST
#echo MSSQL_DB=$MSSQL_DB
#echo MSSQL_USER=$MSSQL_USER
#echo MSSQL_PASS=$MSSQL_PASS
#echo MSSQL_QUERY=$MSSQL_QUERY
#echo MSSQL_CHECK_REGEXP=$MSSQL_CHECK_REGEXP

docker run -i -v /var/run/docker.sock:/var/run/docker.sock emergn/mssql-tools -S $MSSQL_HOST -d $MSSQL_DB -U $MSSQL_USER -P $MSSQL_PASS -Q "$MSSQL_QUERY" | egrep -o "$MSSQL_CHECK_REGEXP"
