#!/bin/bash

if [[ -z "${TELEGRAM_BOT_TOKEN}" || -z "${TELEGRAM_CHAT_ID}" ]]; then
  echo "Required credentials TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID"
  exit 1
fi


curl -X GET "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_CHAT_ID&text=$1"

exit 0
