#!/bin/bash

if [[ -z "${TELEGRAM_BOT_TOKEN}" || -z "${TELEGRAM_CHAT_ID}" ]]; then
  echo "Required credentials TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID"
  exit 1
fi

wget --no-check-certificate -O /dev/null -U NoSuchBrowser/1.0 "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_CHAT_ID&text=$1%20$2%20$3%20$4%20$5%20$6%20$7%20$8%20$9"

exit 0
